server:
  servlet:
    context-path: /api

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: gateway-api
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.neetkee.example.event.PersonChecked

app:
  kafka:
    topic:
      request: Person.Check.Initiated
      reply: Person.Checked
    polling:
      timeout-seconds: 7
      period-seconds: 1
      initial-delay-seconds: 1
      cancel-delay-seconds: 5